### ISSUE TITLE
No menu in typora

### ISSUE THREAD

**Issue by sirrahn** [predr/typora-snap#1]
Hi, I am really keen to install fedora in fedora so thanks for creating the snap. However, when I did install it none of the menus showed up. Everything else seemed to be there by there were simply no menus visible. I just tried to install in on a freshly installed fedora 32. 
Nathan

**Comment by predr** [comment]
Hi. Press Left Alt on keyboard to show main menu.

**Comment by sirrahn** [comment]
Hi, sorry for the slow reply - I only got back to the fedorra 32 
machine yesterday to try it out.

On this computer running fedora 2 the left alt results in the menus 
flashing up just for a moment but then disappears. I tried several 
times but it never stayed long enough to use.

I also installed fedora 33 at home and in this case typora would not 
start up at all. I installed fine from the snap and trued to strt it a 
couple of times. It looke like it would open but nithing appeared.

If I can give you any further information I'd be vey happy to do that 
as I would really like to assist with having a runing version of typora.

Nathan

**Comment by sirrahn** [comment]
I altered the file on the 32 machine: I made it false (with quotation marks removed) and it works well. Thanks

I will have to run typora in terminal from the 33 machine later today because it is at home. I assume I simply run typora from the terminal and output will appear in the terminal?

**Comment by predr** [comment]
> I simply run typora from the terminal and output will appear in the terminal?
Yes, hopefully giving insight why it's not launching. Note: Copy with mouse right-click or Ctrl+Shift+C.

**Comment by sirrahn** [comment]
Here it is:

$ typora
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Snap: Typora config not initialised yet
Segmentation fault (core dumped)

**Comment by predr** [comment]
Thanks, unfortunately no closer to answer. I'll keep looking.

In meantime, you can use [other install options](https://github.com/typora/typora-issues/issues/1457) on that machine and there is also [zipped binary](https://typora.io/linux/Typora-linux-x64.tar.gz).

**Comment by sirrahn** [comment]
Okay, well good luck - I'm not much help with that! Thanks for that 
link, I'll try one of them if I need Typora in the next few days.

**Comment by predr** [comment]
Fedora 33 defaults to Wayland session and it caused issues starting X11 snaps. It's fixed in snapd/Gnome and will come in future updates. Menu flashing issue still remains.

**Comment by sirrahn** [comment]
When I try to run typora on Fedora 33 what I get is:


WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Snap: Typora config not initialised yet
Segmentation fault (core dumped)

**Comment by predr** [comment]
I installed Fedora 33 in virtual machine and tested. After system update Typora starts so I think [fixes](https://forum.snapcraft.io/t/apps-wont-run-and-crash-on-gnome-wayland/20322/14) went trough. Still there is an issue with main menu not showing and there is nothing I can do about that on my end, I have tried. Author of this app does not wanna support Wayland at this time (Electron doesn't support it and that is probably influencing his decision). You can workaround it by using Alt+F to show File menu and other menu shortcuts:

- Alt+F  File
- Alt+E  Edit
- Alt+P  Paragraph
- Alt+O  Format
- Alt+V  View
- Alt+T  Themes
- Alt+H  Help

**Comment by sirrahn** [comment]
Hi,

thanks for all of this. I can open and use on 33 and the shortcuts that you
have provided work. I don't know how they can ignore Wayland because it
will increasingly affect any use in Linux, I imagine. I also wanted to draw
you attention to one more thing, which may also be related. On fedora the
dialogues for opening, saving or exporting files ... don't seem to be able
to represent the font correctly. I've observed this on both 32 and 33.
Sorry to highlight another thing!


[image: image.png]
