### ISSUE TITLE
Fonts in Fedora on open/save dialog

### ISSUE THREAD

**Issue by predr** [predr/typora-snap#3]
> On fedora the dialogues for opening, saving or exporting files ... don't seem to be able to represent the font correctly. I've observed this on both 32 and 33.

I'm not seeing this issue @sirrahn can you try executing these commands in Terminal? Close all apps and execute each command in listed order.

    rm ~/snap/typora/common/.cache/fontconfig/*
    sudo rm /var/cache/fontconfig/*
    rm ~/.cache/fontconfig/*
    fc-cache -r

That should clear and recreate font cache files, then open Typora and see if issue persists.

**Comment by sirrahn** [comment]
Hi

[nathan@ikymaki ~]$ rm ~/snap/typora/common/.cache/fontconfig/*
rm: cannot remove 
'/home/nathan/snap/typora/common/.cache/fontconfig/*': No such file or 
directory
[nathan@ikymaki ~]$ sudo rm /var/cache/fontconfig/*
[sudo] password for nathan:
[nathan@ikymaki ~]$ rm ~/.cache/fontconfig/*
[nathan@ikymaki ~]$ rm ~/.cache/fontconfig/*fc-cache -r
rm: cannot remove '/home/nathan/.cache/fontconfig/*fc-cache': No such 
file or directory

Even though a couple of the files weren't found it was a success and 
the fonts in the dialogues are now fine.

Thanks

**Comment by predr** [comment]
> Even though a couple of the files weren't found it was a success and
the fonts in the dialogues are now fine.

Great to hear, just be careful when executing commands next time. Files weren't found because you combined last two commands into one.
